### ISSUE TITLE
No "HepG2.GENCODE_V33.chr1.rG4_motif.bed.gz" in output directory

### ISSUE THREAD

**Issue by algaebrown** [TF-Chan-Lab/rG4-seeker#2]
Hi Eugene, 
When I run rg4seeker that I installed using `pip install` I ran into the following error
```INFO:root:[Wed Jul  7 19:17:28 2021] Begin rG4 finding for annotation /home/hsher/gencode_coords/gencode.v33.annotation.gff3
Traceback (most recent call last):
  File "/home/hsher/.local/bin/rG4-seeker", line 8, in <module>
    sys.exit(main())
  File "/home/hsher/.local/lib/python3.6/site-packages/rg4seeker/__main__.py", line 223, in main
    main_driver(sys.argv[1])
  File "/home/hsher/.local/lib/python3.6/site-packages/rg4seeker/__main__.py", line 123, in main_driver
    overwrite_reusables)
  File "/home/hsher/.local/lib/python3.6/site-packages/rg4seeker/whitelister.py", line 949, in execute
    rg4_motif_bed = rg4_finding_driver(input_annotation_gff_path, input_genome_fasta_path, prefix, processes, overwrite)
  File "/home/hsher/.local/lib/python3.6/site-packages/rg4seeker/whitelister.py", line 319, in rg4_finding_driver
    return rg4finder.run(processes)
  File "/home/hsher/.local/lib/python3.6/site-packages/rg4seeker/whitelister.py", line 353, in run
    with xopen(temp_bed_file, 'rb') as f:
  File "/home/hsher/.local/lib/python3.6/site-packages/xopen/__init__.py", line 609, in xopen
    return _open_gz(filename, mode, compresslevel, threads)
  File "/home/hsher/.local/lib/python3.6/site-packages/xopen/__init__.py", line 505, in _open_gz
    return igzip.open(filename, mode)
  File "/home/hsher/.local/lib/python3.6/site-packages/isal/igzip.py", line 87, in open
    binary_file = IGzipFile(filename, gz_mode, compresslevel)
  File "/home/hsher/.local/lib/python3.6/site-packages/isal/igzip.py", line 146, in __init__
    super().__init__(filename, mode, compresslevel, fileobj, mtime)
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/rbpamp-8974c585fe33/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/hsher/rg4_seq/20210702_chunkit_rg4seq/rg4seeker_output/HepG2.GENCODE_V33.chr1.rG4_motif.bed.gz'

```
I checked what is in my output directory  `/home/hsher/rg4_seq/20210702_chunkit_rg4seq/rg4seeker_output/`
```
[hsher@tscc-login1 cluster_msg]$ ls /home/hsher/rg4_seq/20210702_chunkit_rg4seq/rg4seeker_output/
HepG2.'GENCODE_V33'.rG4_motif.bed.gz  HepG2.'GENCODE_V33'.rG4_whitelist.bed.gz
HepG2.GENCODE_V33.rG4_motif.bed.gz    HepG2.GENCODE_V33.rG4_whitelist.bed.gz

```

It seems there is only `HepG2.GENCODE_V33.rG4_motif.bed.gz` but not a file with `chr1`.

Here is the complete `config.ini` I fed in:
```[global]
WORKING_DIR = /home/hsher/rg4_seq/20210702_chunkit_rg4seq/rg4seeker_output
SAMPLE_NAME = HepG2
THREADS = 8
NO_OF_ANNOTATIONS = 1
NO_OF_REPLICATES = 2
HAVE_KPDS_CONDITION = False
ALIGNER = STAR
READS_TYPE = PE

[genome]
GENOME_FASTA = /home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa
GENOME_FASTA_FAI = /home/hsher/gencode_coords/GRCh38.primary_assembly.genome.fa.fai # indexing now

[annotation_1]
ANNOTATION_NAME = GENCODE_V33
ANNOTATION_GFF = /home/hsher/gencode_coords/gencode.v33.annotation.gff3

[replicate_1]
LI_BAM_FILE = /home/hsher/rg4_seq/20210702_chunkit_rg4seq/HepG2-rG4seq-Li-rep1Aligned.sortedByCoord.out.singlemap.bam
K_BAM_FILE = /home/hsher/rg4_seq/20210702_chunkit_rg4seq/HepG2-rG4seq-K-rep1Aligned.sortedByCoord.out.singlemap.bam


[replicate_2]
LI_BAM_FILE = /home/hsher/rg4_seq/20210702_chunkit_rg4seq/HepG2-rG4seq-Li-rep2Aligned.sortedByCoord.out.singlemap.bam
K_BAM_FILE = /home/hsher/rg4_seq/20210702_chunkit_rg4seq/HepG2-rG4seq-K-rep2Aligned.sortedByCoord.out.singlemap.bam



```

Thank you!

**Comment by eugenechow** [comment]
Hi algaebrown,

I think you can try cleaning up the directory and run the pipeline again.

`"HepG2.GENCODE_V33.chr1.rG4_motif.bed.gz"` is a temporary file that will be removed when its contents, along with motifs from other chromosomes, are merged into `"HepG2.GENCODE_V33.rG4_motif.bed.gz"`. 

Since `"HepG2.GENCODE_V33.rG4_motif.bed.gz"` is present in the directory and temporary files already cleaned up, rG4-seeker should have completed the rG4 motif prediction stage. 

It is just a guess: maybe the process was terminated and then restarted using the same parameters?

**Comment by algaebrown** [comment]
Thanks Eugene! after cleaning up and re-run it successfully produce the output.
